<?php
/**
 * @author MageSquare Team
 * @copyright Copyright (c) 2021 MageSquare 
 * @package MageSquare_Blog
 */
?>
<?php
/** @var \MageSquare\Blog\Block\Layout\AuthorInfo $block */
/** @var \Magento\Framework\Escaper $escaper */

$author = $block->getAuthorData();
?>

<?php if ($author): ?>
    <h2 class="msblog-article-title">
        <?= $escaper->escapeHtml(__('Articles by %1', $author->getName())); ?>
    </h2>
    <?php if ($author->getDescription()): ?>
        <div class="msblog-author-description">
            <?= $escaper->escapeHtml(nl2br($author->getDescription()), ['br']); ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
