<?php
/**
 * @author MageSquare Team
 * @copyright Copyright (c) 2021 MageSquare 
 * @package MageSquare_Blog
 */
?>
<?php
/**
 * @var \MageSquare\Blog\Block\Featured $block
 * @var \Magento\Framework\Escaper $escaper
 */

$collection = $block->getCollection();
?>

<?php if ($collection->getSize()): ?>
    <div class="block widget block-post-list msblog-post-list">
        <div class="block-title">
            <strong><?= $escaper->escapeHtml(__('Featured Posts')) ?></strong>
        </div>
        <div class="block-content">
            <div class="post-slider">
                <ol class="post-items msblog-slick-slider"
                    data-msblog-js="post-slider"
                    data-mage-init='{"msBlogSlider":{}}'>
                    <?php $iterator = 1; ?>
                    <?php foreach ($collection as $post): ?>
                        <?= /* @noEscape */
                        ($iterator++ == 1) ? '<li class="post-item">' : '</li><li class="post-item">' ?>
                        <div class="post-item-info">
                            <a href="<?= $escaper->escapeUrl($post->getUrl()) ?>" class="post-item-photo">
                                <img src="<?= /* @noEscape */ $post->getListThumbnailSrc() ?>"
                                     alt="<?= $escaper->escapeHtml($post->getTitle()) ?>">
                            </a>
                            <div class="post-item-details">
                                <strong class="post-item-name">
                                    <a title="<?= $escaper->escapeHtml($post->getTitle()) ?>"
                                       href="<?= $escaper->escapeUrl($post->getUrl()) ?>"
                                       class="post-item-link">
                                        <?= $escaper->escapeHtml($post->getTitle()) ?>
                                    </a>
                                </strong>
                            </div>
                        </div>
                        <?= ($iterator == $collection->getSize() + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>
<?php endif; ?>
