<?php
/**
 * @author MageSquare Team
 * @copyright Copyright (c) 2021 MageSquare 
 * @package MageSquare_Blog
 */
?>
<?php
/** @var \MageSquare\Blog\Block\Content\Lists $block */
/** @var \Magento\Framework\Escaper $escaper */

$collection = $block->getCollection();
?>

<div class="msblog-container-list">
    <?= $block->getChildHtml('additional') ?>
    <?php if ($block->isCanRender()): ?>
        <?php foreach ($collection as $post): ?>
            <div class="msblog-post-container">
                <div class="msblog-wrapper">
                    <?php $imageSrc = $post->getListThumbnailSrc(); ?>
                    <?php if ($imageSrc): ?>
                        <a href="<?= $escaper->escapeUrl($post->getUrl()); ?>"
                           title="<?= $escaper->escapeHtml($post->getTitle()); ?>">
                            <img src="<?= $escaper->escapeUrl($imageSrc); ?>"
                                 class="msblog-image"
                                 alt="<?= $escaper->escapeHtml($post->getThumbnailAlt()); ?>" />
                        </a>
                    <?php endif; ?>
                </div>
                <div class="msblog-tags tag1">
                    <?= $block->getTagsHtml($post); ?>
                </div>
                <div class="msblog-footer">
                        <div class="msblog-features">
                            <?= $block->getCategoriesHtml($post); ?>
                            <?= $block->getAuthorHtml($post); ?>
                            <?= $block->getShortCommentsHtml($post); ?>
                        </div>
                   
                    </div>
                <div class="msblog-content">
                    <h2 class="msblog-title titlenew">
                        <a href="<?= $escaper->escapeUrl($post->getUrl()); ?>"
                           class="msblog-headline"
                           title=" <?= $escaper->escapeHtml($post->getTitle()); ?>"
                        >
                            <?= $escaper->escapeHtml($post->getTitle()); ?>
                        </a>
                    </h2>
                     
                    <div class="msblog-shot">
                        <?= /* @noEscape */ $post->getShortContent(); ?>
                            <a class="msblog-read msblog-read1 btn btn-primary"
                               href="<?= $escaper->escapeUrl($block->getReadMoreUrl($post)); ?>"
                               title="<?= $escaper->escapeHtml(__('Read More')); ?>">
                                <?= $escaper->escapeHtml(__('Read More...')); ?>
                               
                            </a>
                    </div>
                    <div class="msblog-bottom">
                        <div class="msblog-date">
                            <?=  $escaper->escapeHtml($block->renderDate($post->getPublishedAt())); ?>
                        </div>
                        <?php if ($block->getSettingHelper()->getDisplayViews()): ?>
                            <span
                                class="views msblog-views"
                                data-msblog-js="views-counter"
                                data-post-id="<?= (int) $post->getPostId() ?>"
                            >
                            <?= $escaper->escapeHtml(__('%1 view(s)', $post->getViews())); ?>
                        </span>
                        <?php endif; ?>
                    </div>
                </div>
               
                
            </div>
        <?php endforeach; ?>
        <?= $block->getToolbarHtml(); ?>
    <?php else: ?>
        <div class="message notice">
            <div><?= $escaper->escapeHtml(__('There are no posts yet.')); ?></div>
        </div>
    <?php endif; ?>
</div>
<div class="msblog-overlay" data-msblog-js="overlay"></div>

<?php if ($block->isCanRender()): ?>
    <script type="text/x-magento-init">
    {
        ".msblog-container-list": {
             "msBlogViewsList": {}
        }
    }
    </script>
<?php endif; ?>

<script type="text/x-magento-init">
{
    "*": {
         "msBlogAccord": {}
    }
}
</script>
