<?php
/**
 * @author MageSquare Team
 * @copyright Copyright (c) 2021 MageSquare 
 * @package MageSquare_Blog
 */
?>
<?php
/** @var \MageSquare\Blog\Block\Sidebar\Recentcomments $block */

$collection = $block->getCommentsCollection();
?>

<?php if ($block->getDisplay() && $collection && $collection->getSize()): ?>
    <div class="msblog-recentcomments sidebar-item">
        <div class="msblog-amp-title">
            <?= $block->escapeHtml($block->getBlockHeader()); ?>
        </div>
        <?php foreach ($collection as $comment): ?>
            <div class="msblog-recent-comment item">
                <a class="msblog-sidebar-message" href="<?= $block->escapeUrl($comment->getUrl()); ?>">
                    <?= $block->escapeHtml($comment->getMessage()); ?>
                </a>
                <?php if ($block->needShowDate()): ?>
                    <div class="msblog-sidebar-date">
                        <?= /* @noEscape */ $block->renderDate($comment->getCreatedAt()); ?>
                    </div>
                <?php endif; ?>
                <?php if ($block->needShowThesis()): ?>
                    <div class="msblog-comment-thesis">
                        <?= /* @noEscape */ $block->getStrippedContent($comment->getMessage()); ?>
                    </div>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
