<?php
/**
 * @author MageSquare Team
 * @copyright Copyright (c) 2021 MageSquare 
 * @package MageSquare_Blog
 */
?>
<?php $tags = $block->getTags(); ?>
<?php if ($tags && count($tags)): ?>
    <?php foreach ($tags as $tag): ?>
        <a class="msblog-tag"
           href="<?= $block->escapeUrl($tag->getUrl()); ?>"
           title="<?= $block->escapeHtml($tag->getName()); ?>">
            <?= $block->escapeHtml($tag->getName()); ?>
        </a>
    <?php endforeach; ?>
<?php endif; ?>
