<?php
/**
 * @author MageSquare Team
 * @copyright Copyright (c) 2021 MageSquare 
 * @package MageSquare_Blog
 */
?>
<?php
/** @var $block \MageSquare\Blog\Block\Comments\Message */
/** @var \Magento\Framework\Escaper $escaper */

$myCommentClass = $block->isMyComment() ? 'my-comment' : '';
$svgLink = $block->getViewFileUrl('MageSquare_Blog::images/sprite.svg');
$isReply = (bool)$block->getMessage()->getReplyTo();
$levelTopClass = !$isReply ? '-level-top' : '';
$colorThemeClass = $block->getColorClass();
?>

<div class="msblog-comment <?= $escaper->escapeHtmlAttr($levelTopClass); ?> <?= $escaper->escapeHtmlAttr($colorThemeClass); ?>"
     data-msblog-js="comment-item"
     id="ms-blog-comment-<?= $escaper->escapeHtmlAttr($block->getMessageId()); ?>">
    <div class="msblog-comment-content <?= $escaper->escapeHtmlAttr($myCommentClass); ?>">
        <div class="msblog-header">
            <div class="msblog-author authorname">
                <svg class="msblog-svg user <?= $escaper->escapeHtmlAttr($colorThemeClass); ?>">
                    <use xlink:href="<?= $escaper->escapeUrl($svgLink); ?>#user"></use>
                </svg>
                <?= $escaper->escapeHtml($block->getAuthor()); ?>
            </div>
        </div>
        <div class="msblog-date">
                <?= $escaper->escapeHtml($block->getDate()); ?>
        </div>
        <?php if ($block->getNeedApproveMessage()): ?>
            <div class="msblog-thesis">
                <?= $escaper->escapeHtml($block->getContent()); ?>
            </div>
            <div class="msblog-willapprove">
                <?= $escaper->escapeHtml(__('This comment will become public after administrator approval.')); ?>
            </div>
        <?php endif; ?>
        <?php if (!$block->getNeedApproveMessage()): ?>
            <div class="msblog-thesis">
                <?= $escaper->escapeHtml($block->getContent()); ?>
                <div class="msblog-reply">
                <a data-id="<?= $escaper->escapeHtmlAttr($block->getMessageId()); ?>"
                   class="msblog-button"
                   title="<?= $escaper->escapeHtmlAttr(__('Reply')); ?>"
                   data-msblog-js="reply-to"
                   href="#am-comment-form-<?= $escaper->escapeHtmlAttr($block->getMessageId()); ?>" >
                    <svg class="msblog-icon" width="12" height="8" fill="none">
                        <use xlink:href="<?= $escaper->escapeUrl($svgLink); ?>#reply"></use>
                    </svg>
                    <?= $escaper->escapeHtml(__('Reply')); ?>
                </a>
                <?php if (!$isReply): ?>
                    <button class="msblog-button -toggle -clear"
                            title="<?= $escaper->escapeHtmlAttr(__('Show comments')); ?>"
                            data-id="<?= $escaper->escapeHtmlAttr($block->getMessageId()); ?>"
                            data-msblog-js="toggle-replies">
                        <svg class="msblog-icon" width="9" height="5" fill="none">
                            <use xlink:href="<?= $escaper->escapeUrl($svgLink); ?>#arrow"></use>
                        </svg>
                        <span><?= $escaper->escapeHtml(__('Comments')); ?></span>
                        <span class="msblog-count" data-msblog-js="comments-count"></span>
                    </button>
                <?php endif; ?>

            </div>
            </div>
            
        <?php endif; ?>
    </div>
    <div class="msblog-replies-block <?= $escaper->escapeHtmlAttr($levelTopClass); ?>"
        <?php if (!$isReply): ?>
        data-msblog-js="replies-block"
        <?php endif; ?>
    >
        <div class="msblog-comment-reply"
             id="am-comment-form-<?= $escaper->escapeHtmlAttr($block->getMessageId()); ?>"
             style="display: none;">
        </div>

        <div class="msblog-replies"
             data-msblog-js="replies"
             data-reply-id="<?= $escaper->escapeHtmlAttr($block->getMessageId()); ?>"><?= $block->getRepliesHtml(); ?></div>
    </div>
</div>
