<?php
/**
 * @author MageSquare Team
 * @copyright Copyright (c) 2021 MageSquare 
 * @package MageSquare_Blog
 */
?>
<?php
/** @var \MageSquare\Blog\Block\Content\Post\Details $block */
?>

<?php if (count($block->getCategories())) : ?>
    <?= $block->escapeHtml(__("Posted in: ")); ?>
    <?php $isFirst = true; ?>
    <?php foreach ($block->getCategories() as $category) : ?>
        <?php if (!$isFirst) : ?>
            ,&nbsp;
        <?php endif ?>
        <a href="<?= $block->escapeUrl($category->getUrl()); ?>" class="category">
            <?= $block->escapeHtml($category->getName()); ?>
        </a>
        <?php $isFirst = false; ?>
    <?php endforeach; ?>
<?php endif; ?>
