<?php
/**
 * @author MageSquare Team
 * @copyright Copyright (c) 2021 MageSquare 
 * @package MageSquare_Blog
 */
?>
<?php
/** @var \MageSquare\Blog\Block\Content\Post\Details $block */
/** @var \Magento\Framework\Escaper $escaper */

$post = $block->getPost();
?>
<?php if ($block->isShowAuthorInfo() && $post->getPostedBy()): ?>
    <div class="msblog-wrap">
        <svg class="msblog-svg user <?= $escaper->escapeHtml($block->getColorClass()); ?>">
            <use xlink:href="<?= $escaper->escapeUrl($block->getViewFileUrl('MageSquare_Blog::images/sprite.svg')); ?>#user"></use>
        </svg>
        <div class="msblog-item -author">
            <?= $escaper->escapeHtml(__('By ')); ?>
            <a rel="author"
               class="msblog-ref"
               href="<?= $escaper->escapeUrl($post->getAuthor()->getUrl()); ?>"
               title="<?= $escaper->escapeHtml($post->getPostedBy()); ?>">
                <?= $escaper->escapeHtml($post->getPostedBy()); ?>
            </a>
        </div>
    </div>
<?php endif; ?>
