<?php
/**
 * @author MageSquare Team
 * @copyright Copyright (c) 2021 MageSquare 
 * @package MageSquare_Blog
 */
?>
<?php
/**
 * @var \MageSquare\Blog\Block\Content\Post\RelatedProducts $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \MageSquare\Blog\ViewModel\Posts\RelatedProducts $viewModel
 */

$viewModel = $block->getViewModel();
$productsCount = count($viewModel->getPostProducts());
?>

<?php if ($viewModel->isCanRender()): ?>
    <div class="msblog-related-wrapper -related-products">
        <div class="msblog-title">
            <?= $escaper->escapeHtml($viewModel->getRelatedProductsBlockName()) ?>
        </div>
        <ul class="msblog-related-grid msblog-grid-list msblog-slick-slider"
            data-mage-init='{"msBlogSlider": {
                "dots": true,
                "centerMode": false,
                "infinite": false,
                "slidesToShow": <?= $escaper->escapeHtml($productsCount > 4 ? 4 : $productsCount) ?>,
                "slidesToScroll": 1,
                "responsive": [
                    {
                        "breakpoint": 1024,
                        "settings": {
                            "slidesToShow": <?= $escaper->escapeHtml($productsCount > 3 ? 3 : $productsCount) ?>
                        }
                    },
                    {
                        "breakpoint": 768,
                        "settings": {
                            "slidesToShow": <?= $escaper->escapeHtml($productsCount > 2 ? 2 : $productsCount) ?>
                        }
                    },
                    {
                        "breakpoint": 480,
                        "settings": {
                            "slidesToShow": 1
                        }
                    },
                    {
                        "breakpoint": 320,
                        "settings": {
                            "slidesToShow": 1,
                            "arrows": false
                        }
                    }
                ]
            }}'
        >
        <?php foreach ($viewModel->getPostProducts() as $product): ?>
            <div class="msblog-item-product product-item">
                <a class="product photo product-item-photo"
                   href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                    <?= /* @noEscape */ $viewModel->getImageHtml($product) ?>
                </a>
                <div class="msblog-details">
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
                               title="<?= $escaper->escapeHtmlAttr($product->getName()) ?>">
                                <?= $escaper->escapeHtml($product->getName()) ?>
                            </a>
                        </strong>

                        <?= /* @noEscape */ $viewModel->getReviewsHtml($product) ?>
                    </div>

                    <?= /* @noEscape */ $viewModel->getProductPriceHtml($product) ?>
                </div>
            </div>
        <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
