<?php
/**
 * @author MageSquare Team
 * @copyright Copyright (c) 2021 MageSquare 
 * @package MageSquare_Blog
 */
?>
<?php
/** @var \MageSquare\Blog\Block\Sidebar\Category\TreeRenderer $block */
/** @var \Magento\Framework\Escaper $escaper */

$collection = $block->getCollection();
?>

<?php if (count($collection)): ?>
    <?php foreach ($collection as $category): ?>
        <?php $activeClass = $category->getIsActive() ? 'active' : ''; ?>
        <li class="msblog-category <?= /* @noEscape */ $activeClass; ?> msblog-category-<?= (int)$category->getId(); ?>">
            <a class="msblog-link newmsblog-link"
               title="<?= $escaper->escapeHtmlAttr($category->getName()); ?>"
               href="<?= $escaper->escapeUrl($category->getUrl()); ?>">
                <?= $escaper->escapeHtml($category->getName()); ?>
                 <span class="msblog-category-count">(<?= $escaper->escapeHtml($block->getPostsCount($category->getId())); ?>)</span>
            </a>


            <?php if ($category->hasActiveChildren()): ?>
                <ul class="msblog-categories -level<?= $category->getLevel() + 1; ?>">
                    <?= /* @noEscape */ $block->renderChildrenItems((int)$category->getCategoryId()); ?>
                </ul>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
<?php endif; ?>
