<?php
/**
 * @author MageSquare Team
 * @copyright Copyright (c) 2021 MageSquare 
 * @package MageSquare_Blog
 */
?>
<?php /** @var \MageSquare\Blog\Block\Adminhtml\Posts\Edit\View $block */ ?>

<div class="ampost_views">
    <label>
        <span class="msblog_views_label"><?= $block->escapeHtml(__('Views:')) ?></span> <?= $block->escapeHtml($block->getViews()) ?>
    </label>
</div>

<div class="ampost_likes">
    <label>
        <span class="msblog_likes_label"><?= $block->escapeHtml(__('Like:')) ?></span> <?= $block->escapeHtml($block->getLikes()) ?>
    </label>
</div>

<div class="ampost_dislikes">
    <label>
        <span class="msblog_dislikes_label"><?= $block->escapeHtml(__('Dislike:')) ?></span> <?= $block->escapeHtml($block->getDisLikes()) ?>
    </label>
</div>
