<?php
/**
 * @author MageSquare Team
 * @copyright Copyright (c) 2021 MageSquare 
 * @package MageSquare_Blog
 */
?>
<?php
/**
 * @var \MageSquare\Blog\Block\Html\Header\Logo $block
 */
?>

<div class="msblog-amp-nav" on="tap:navigation.toggle" role="button" tabindex="0" id="ampblog-top">
    <i class="fas fa-bars amicon msblog-amp-icon"></i>
</div>

<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt(); ?>
    <span data-action="toggle-nav" class="action nav-toggle"></span>
<?php if ($block->isHomePage()) : ?>
    <strong class="logo">
<?php else : ?>
    <a class="msblog-amp-link msblog-amp-logo"
    href="<?= $block->escapeUrl($block->getUrl('')) ?>"
    title="<?= $block->escapeHtml($storeName) ?>">
<?php endif; ?>
    <amp-img alt="<?= $block->escapeHtml($block->getLogoAlt()); ?>"
             src="<?= $block->escapeUrl($block->getLogoUrl()); ?>"
        <?= /* @noEscape */ $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : 'width="150"'; ?>
        <?= /* @noEscape */ $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : 'height="60"'; ?>>
    </amp-img>
<?php if ($block->isHomePage()) : ?>
    </strong>
<?php else : ?>
    </a>
<?php endif; ?>
