<?php
/**
 * @author MageSquare Team
 * @copyright Copyright (c) 2021 MageSquare 
 * @package MageSquare_Blog
 */
?>
<?php
/** @var \MageSquare\Blog\Block\Content\Lists $block */

$collection = $block->getCollection();
?>

<div class="msblog-grid-wrap msblog-post-wrap">
    <?php if ($collection && $collection->getSize()): ?>
        <?php foreach ($collection as $post): ?>
            <div class="list-item">
                <h3>
                    <a class="msblog-title" href="<?= $block->escapeUrl($post->getUrl()); ?>"
                       title="<?= $block->escapeHtml($post->getTitle()); ?>">
                        <?= $block->escapeHtml($post->getTitle()); ?>
                    </a>
                </h3>

                <?php if ($post->getListThumbnailSrc()): ?>
                    <div class="amp-img-container">
                        <a href="<?= $block->escapeUrl($post->getUrl()); ?>"
                           title="<?= $block->escapeHtml($post->getTitle()); ?>">
                            <amp-img alt="<?= $block->escapeHtml($post->getThumbnailAlt()); ?>"
                                     src="<?= $block->escapeUrl($post->getListThumbnailSrc()); ?>"
                                     layout="fill">
                            </amp-img>
                        </a>
                    </div>
                <?php endif; ?>

                <div class="post-header">
                    <?= $block->getAmpHeaderHtml($post); ?>
                </div>

                <div class="short-content">
                    <?= /* @noEscape */ $post->getShortContent(); ?>
                </div>

                <div class="msblog-post-tags">
                    <div class="msblog-categories">
                        <?= $block->getCategoriesHtml($post, true); ?>
                    </div>
                    <div class="msblog-tags">
                        <?= $block->getTagsHtml($post, true); ?>
                    </div>
                </div>

                <a class="button am-readmore" href="<?= $block->escapeUrl($block->getReadMoreUrl($post)); ?>"
                   title="<?= $block->escapeHtml(__("Read More")); ?>">
                    <?= $block->escapeHtml(__("Read More")); ?>
                </a>
            </div>
        <?php endforeach; ?>
        <div class="msblog-toolbar">
            <?= $block->getToolbarHtml(true); ?>
        </div>
    <?php else: ?>
        <p>
            <?= $block->escapeHtml(__("There are no posts yet.")); ?>
        </p>
    <?php endif; ?>
</div>
