<?php
/**
 * @author MageSquare Team
 * @copyright Copyright (c) 2021 MageSquare 
 * @package MageSquare_Blog
 */
?>
<?php
/** @var \MageSquare\Blog\Block\Layout $block */

$ampSidebarSide = $block->hasMobileLeftColumn() ? 'left' : 'right';
?>

<amp-sidebar id="sidebar"
             layout="nodisplay"
             side="<?= /* @noEscape */ $ampSidebarSide; ?>"
             class="msblog-amp-sidebar">
    <div class="amp-close-image"
         on="tap:sidebar.close"
         role="button"
         tabindex="0">&#10799;</div>
    <div class="msblog-sidebar-content msblog-amp-navigation">
        <?php if ($block->hasMobileLeftColumn()) : ?>
            <?php foreach ($block->getMobileBlocks('left_side') as $alias) : ?>
                <?= $block->getSidebarBlockHtml($alias); ?>
            <?php endforeach; ?>
        <?php endif; ?>

        <?php if ($block->hasMobileRightColumn()) : ?>
            <?php foreach ($block->getMobileBlocks('right_side') as $alias) : ?>
                <?= $block->getSidebarBlockHtml($alias); ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</amp-sidebar>

<div class="amp-blog-nav" on="tap:sidebar.toggle" role="button" tabindex="0">
    <?=  $block->escapeHtml(__("Blog's Menu")); ?>
    <i class="fas fa-chevron-right arrow"></i>
</div>
