<?php
/**
 * @author MageSquare Team
 * @copyright Copyright (c) 2021 MageSquare 
 * @package MageSquare_Blog
 */
?>
<?php
/** @var \MageSquare\Blog\Block\Content\Lists $block */
/** @var \Magento\Framework\Escaper $escaper */

$collection = $block->getCollection();
?>

<div class="msblog-list-wrap msblog-post-wrap">
    <?php if ($collection && $collection->getSize()): ?>
        <div class="msblog-list">
            <?php foreach ($collection as $post): ?>
                <div class="msblog-post">
                    <h2>
                        <a class="msblog-title" href="<?= $escaper->escapeUrl($post->getUrl()); ?>"
                           title="<?= $escaper->escapeHtml($post->getTitle()); ?>">
                            <?= $escaper->escapeHtml($post->getTitle()); ?>
                        </a>
                    </h2>

                    <?php if ($post->getListThumbnailSrc()): ?>
                        <div class="amp-img-container">
                            <a href="<?= $escaper->escapeUrl($post->getUrl()); ?>"
                               title="<?= $escaper->escapeHtml($post->getTitle()); ?>">
                                <amp-img alt="<?= $escaper->escapeHtml($post->getThumbnailAlt()); ?>"
                                         src="<?= $escaper->escapeUrl($post->getListThumbnailSrc()); ?>"
                                         layout="fill">
                                </amp-img>
                            </a>
                        </div>
                    <?php endif; ?>

                    <div class="post-header">
                        <?= $block->getAmpHeaderHtml($post); ?>
                    </div>

                    <div class="am-content">
                        <?= /* @noEscape */ $post->getShortContent(); ?>
                    </div>

                    <div class="msblog-post-tags">
                        <div class="msblog-categories">
                            <?= $block->getCategoriesHtml($post, true); ?>
                        </div>
                        <div class="msblog-tags">
                            <?= $block->getTagsHtml($post, true); ?>
                        </div>
                    </div>

                    <div class="am-details">
                        <a class="button am-readmore" href="<?= $escaper->escapeUrl($block->getReadMoreUrl($post)); ?>"
                           title="<?= $escaper->escapeHtml(__("Read More...")); ?>">
                            <?= $escaper->escapeHtml(__("Read More...")); ?>
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="msblog-toolbar">
            <?= $block->getToolbarHtml(true); ?>
        </div>
    <?php else: ?>
        <p>
            <?= $escaper->escapeHtml(__("There are no posts yet.")); ?>
        </p>
    <?php endif; ?>
</div>
