<?php
/**
 * @author MageSquare Team
 * @copyright Copyright (c) 2021 MageSquare 
 * @package MageSquare_Blog
 */
?>
<!doctype html>
<html ⚡>
<head>
    <?= $block->getChildHtml('head') ?>
</head>
<body id="page-top">
    <?= $block->getChildHtml('global_notices') ?>
    <?= $block->getChildHtml('header') ?>
    <?= $block->getChildHtml('content') ?>
    <?= $block->getChildHtml('footer') ?>
    <?= $block->getChildHtml('amp_body_end') ?>
</body>
</html>
