<?php
/**
 * @author MageSquare Team
 * @copyright Copyright (c) 2021 MageSquare 
 * @package MageSquare_Blog
 */
?>
<?php /**  @var $block \MageSquare\Blog\Block\Adminhtml\System\Config\Form\Element\Colors\Render */ ?>

<select class=" select" name="groups[tags][fields][presetted_colors][value]" id="msblog_tags_presetted_colors">
    <?php foreach ($block->getSchemes() as $value => $label): ?>
        <option value="<?= $block->escapeHtml($value); ?>">
            <?= $block->escapeHtml($label); ?>
        </option>
    <?php endforeach; ?>
</select>

<button onclick="applyColorScheme();"
        class="scalable apply"
        type="button"
        title="<?= $block->escapeHtml(__("Apply")); ?>"
        id="msblog_tags_presetted_colors_apply">
    <span>
        <span>
            <span><?= $block->escapeHtml(__("Apply")); ?></span>
        </span>
    </span>
</button>

<div class="fixed"></div>

<script type="text/javascript">
    var colorSchemes = <?= /* @noEscape */ $block->getSchemesDataJson(); ?>;
    var applyColorScheme = function() {
        var key = $('msblog_tags_presetted_colors').value;
        if (key) {
            if (colorSchemes[key]) {
                var data = colorSchemes[key];

                for (rowKey in data) {
                    var id = 'msblog_tags_mt_' + rowKey;
                    var element = $(id);
                    if (element) {
                        element.value = '#' + data[rowKey];
                        jQuery(element).css("backgroundColor", '#' + data[rowKey]);
                    }
                }
            }
        }
        return false;
    };
</script>
